name: daily-cron
on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://days-since-last-chalga-song.vercel.app/api/trpc/videos.updateVideoList' \
          --header 'authorization: ${{ secrets.SECRET_KEY }}'
